# -*- coding: utf-8 -*-
"""Abbas Ahammed-MD5 String Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E2apeIJJnNOjlKoZA2umyxQ2mZU89z3t
"""

import hashlib
str = "Hello World "
#encoding the str using encode ()
# then sending to md5()
result = hashlib.md5	 (str.encode ())
# printing the equivalent hexadecimal value
print("The hexadecimal equivalent of hash is:",end =" ")
print (result . hexdigest ())
#
print("Enter the  String/Text to generate your MD5 Data:")
text =input("Enter your String/Text Here:")
hash_obj = hashlib.md5(text.encode())
md5_hash = hash_obj.hexdigest()
print("The GENERATED MD5 of String/Text data is:- ",md5_hash)
print("FINAL OUTPUT:-",text,"=",md5_hash)